openapi: 3.0.0
info:
  title: CodeVibe
  version: 1.0.0
servers:
  - url: http://localhost:8080
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    basicAuth:
      type: http
      scheme: basic
tags:
  - name: Register
  - name: Login
  - name: Adverts
  - name: Users
  - name: Adverts Basic Auth
paths:
  /users/register:
    post:
      tags:
        - Register
      summary: Register
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: testuser22
                password: testpassword22
                email: testemail
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          headers:
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-XSS-Protection:
              schema:
                type: integer
                example: '0'
            Cache-Control:
              schema:
                type: string
                example: no-cache, no-store, max-age=0, must-revalidate
            Pragma:
              schema:
                type: string
                example: no-cache
            Expires:
              schema:
                type: integer
                example: '0'
            X-Frame-Options:
              schema:
                type: string
                example: DENY
            Content-Type:
              schema:
                type: string
                example: application/json
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Date:
              schema:
                type: string
                example: Fri, 30 Aug 2024 09:21:22 GMT
            Keep-Alive:
              schema:
                type: string
                example: timeout=60
            Connection:
              schema:
                type: string
                example: keep-alive
          content:
            application/json:
              schema:
                type: object
              example:
                jwtToken: >-
                  eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlcjIyIiwiaWF0IjoxNzI1MDA5NjgyLCJleHAiOjE3MjUwNDU2ODJ9.91dAo3a4bBYrSM1utND9cA8Hl-2n9j1L1AwkY94t0HQ
  /users/login:
    post:
      tags:
        - Login
      summary: Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: Admin
                password: Admin
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          headers:
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-XSS-Protection:
              schema:
                type: integer
                example: '0'
            Cache-Control:
              schema:
                type: string
                example: no-cache, no-store, max-age=0, must-revalidate
            Pragma:
              schema:
                type: string
                example: no-cache
            Expires:
              schema:
                type: integer
                example: '0'
            X-Frame-Options:
              schema:
                type: string
                example: DENY
            Content-Type:
              schema:
                type: string
                example: application/json
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Date:
              schema:
                type: string
                example: Fri, 30 Aug 2024 09:21:18 GMT
            Keep-Alive:
              schema:
                type: string
                example: timeout=60
            Connection:
              schema:
                type: string
                example: keep-alive
          content:
            application/json:
              schema:
                type: object
              example:
                jwtToken: >-
                  eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBZG1pbiIsImlhdCI6MTcyNTAwOTY3OCwiZXhwIjoxNzI1MDQ1Njc4fQ.JSMzqRwIEhoH9ksyo4WDxZ57No17dk7qDuxngy-O7kY
  /adverts:
    get:
      tags:
        - Adverts Basic Auth
      summary: GET Adverts Sorted By Price
      security:
        - basicAuth: []
      parameters:
        - name: sortBy
          in: query
          schema:
            type: string
          example: price
      responses:
        '200':
          description: OK
          headers:
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-XSS-Protection:
              schema:
                type: integer
                example: '0'
            Cache-Control:
              schema:
                type: string
                example: no-cache, no-store, max-age=0, must-revalidate
            Pragma:
              schema:
                type: string
                example: no-cache
            Expires:
              schema:
                type: integer
                example: '0'
            X-Frame-Options:
              schema:
                type: string
                example: DENY
            Content-Type:
              schema:
                type: string
                example: application/json
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Date:
              schema:
                type: string
                example: Fri, 30 Aug 2024 09:20:56 GMT
            Keep-Alive:
              schema:
                type: string
                example: timeout=60
            Connection:
              schema:
                type: string
                example: keep-alive
          content:
            application/json:
              schema:
                type: object
              example:
                - id: 9
                  title: Car I
                  fuelType: Petrol
                  price: 13000
                  mileage: 7000
                  firstRegistration: '2022-04-25'
                  createdAt: '2024-08-30T07:35:16.875+00:00'
                  updatedAt: '2024-08-30T07:35:16.875+00:00'
                  new: true
                - id: 5
                  title: Car E
                  fuelType: Petrol
                  price: 14000
                  mileage: 4000
                  firstRegistration: '2022-12-10'
                  createdAt: '2024-08-30T07:35:16.875+00:00'
                  updatedAt: '2024-08-30T07:35:16.875+00:00'
                  new: true
                - id: 1
                  title: Car A
                  fuelType: Petrol
                  price: 15000
                  mileage: 5000
                  firstRegistration: '2022-01-15'
                  createdAt: '2024-08-30T07:35:16.875+00:00'
                  updatedAt: '2024-08-30T07:35:16.875+00:00'
                  new: true
                - id: 6
                  title: Car F
                  fuelType: Diesel
                  price: 16000
                  mileage: 15000
                  firstRegistration: '2019-08-22'
                  createdAt: '2024-08-30T07:35:16.875+00:00'
                  updatedAt: '2024-08-30T07:35:16.875+00:00'
                  new: false
                - id: 2
                  title: Car B
                  fuelType: Diesel
                  price: 18000
                  mileage: 12000
                  firstRegistration: '2020-03-10'
                  createdAt: '2024-08-30T07:35:16.875+00:00'
                  updatedAt: '2024-08-30T07:35:16.875+00:00'
                  new: false
                - id: 8
                  title: Car H
                  fuelType: Hybrid
                  price: 19000
                  mileage: 9500
                  firstRegistration: '2021-11-30'
                  createdAt: '2024-08-30T07:35:16.875+00:00'
                  updatedAt: '2024-08-30T07:35:16.875+00:00'
                  new: false
                - id: 4
                  title: Car D
                  fuelType: Hybrid
                  price: 22000
                  mileage: 8000
                  firstRegistration: '2021-07-05'
                  createdAt: '2024-08-30T07:35:16.875+00:00'
                  updatedAt: '2024-08-30T07:35:16.875+00:00'
                  new: false
                - id: 7
                  title: Car G
                  fuelType: Electric
                  price: 30000
                  mileage: 1000
                  firstRegistration: '2023-02-18'
                  createdAt: '2024-08-30T07:35:16.875+00:00'
                  updatedAt: '2024-08-30T07:35:16.875+00:00'
                  new: true
                - id: 3
                  title: Car C
                  fuelType: Electric
                  price: 33000
                  mileage: 12000
                  firstRegistration: '2023-06-20'
                  createdAt: '2024-08-30T07:35:16.875+00:00'
                  updatedAt: '2024-08-30T09:19:49.564+00:00'
                  new: false
                - id: 14
                  title: Car Test
                  fuelType: Electric
                  price: 50000
                  mileage: 10
                  firstRegistration: '2024-09-08'
                  createdAt: '2024-08-30T09:19:30.666+00:00'
                  updatedAt: '2024-08-30T09:19:30.668+00:00'
                  new: false
                - id: 12
                  title: Car Test
                  fuelType: Electric
                  price: 50000
                  mileage: 10
                  firstRegistration: '2024-09-08'
                  createdAt: '2024-08-30T08:47:41.455+00:00'
                  updatedAt: '2024-08-30T08:47:41.459+00:00'
                  new: false
                - id: 11
                  title: Car Test
                  fuelType: Electric
                  price: 50000
                  mileage: 10
                  firstRegistration: '2024-09-08'
                  createdAt: '2024-08-30T08:27:34.909+00:00'
                  updatedAt: '2024-08-30T08:27:34.913+00:00'
                  new: false
                - id: 13
                  title: Car Test
                  fuelType: Electric
                  price: 50000
                  mileage: 10
                  firstRegistration: '2024-09-08'
                  createdAt: '2024-08-30T08:52:02.820+00:00'
                  updatedAt: '2024-08-30T08:52:02.822+00:00'
                  new: false
    post:
      tags:
        - Adverts Basic Auth
      summary: POST Create Advert
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                title: Car Test
                fuelType: Electric
                price: 50000
                mileage: 10
                firstRegistration: '2024-09-08'
                new: false
      security:
        - basicAuth: []
      responses:
        '201':
          description: Created
          headers:
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-XSS-Protection:
              schema:
                type: integer
                example: '0'
            Cache-Control:
              schema:
                type: string
                example: no-cache, no-store, max-age=0, must-revalidate
            Pragma:
              schema:
                type: string
                example: no-cache
            Expires:
              schema:
                type: integer
                example: '0'
            X-Frame-Options:
              schema:
                type: string
                example: DENY
            Content-Type:
              schema:
                type: string
                example: application/json
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Date:
              schema:
                type: string
                example: Fri, 30 Aug 2024 09:20:59 GMT
            Keep-Alive:
              schema:
                type: string
                example: timeout=60
            Connection:
              schema:
                type: string
                example: keep-alive
          content:
            application/json:
              schema:
                type: object
              example:
                id: 15
                title: Car Test
                fuelType: Electric
                price: 50000
                mileage: 10
                firstRegistration: '2024-09-08T00:00:00.000+00:00'
                createdAt: null
                updatedAt: null
                new: false
  /adverts/3:
    get:
      tags:
        - Adverts Basic Auth
      summary: GET One Advert
      security:
        - basicAuth: []
      responses:
        '200':
          description: OK
          headers:
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-XSS-Protection:
              schema:
                type: integer
                example: '0'
            Cache-Control:
              schema:
                type: string
                example: no-cache, no-store, max-age=0, must-revalidate
            Pragma:
              schema:
                type: string
                example: no-cache
            Expires:
              schema:
                type: integer
                example: '0'
            X-Frame-Options:
              schema:
                type: string
                example: DENY
            Content-Type:
              schema:
                type: string
                example: application/json
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Date:
              schema:
                type: string
                example: Fri, 30 Aug 2024 09:20:51 GMT
            Keep-Alive:
              schema:
                type: string
                example: timeout=60
            Connection:
              schema:
                type: string
                example: keep-alive
          content:
            application/json:
              schema:
                type: object
              example:
                id: 3
                title: Car C
                fuelType: Electric
                price: 33000
                mileage: 12000
                firstRegistration: '2023-06-20'
                createdAt: '2024-08-30T07:35:16.875+00:00'
                updatedAt: '2024-08-30T09:19:49.564+00:00'
                new: false
    put:
      tags:
        - Adverts Basic Auth
      summary: PUT Update Advert
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                title: Car C
                fuelType: Electric
                price: 33000
                mileage: 12000
                firstRegistration: '2023-06-20'
                new: false
      security:
        - basicAuth: []
      responses:
        '200':
          description: OK
          headers:
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-XSS-Protection:
              schema:
                type: integer
                example: '0'
            Cache-Control:
              schema:
                type: string
                example: no-cache, no-store, max-age=0, must-revalidate
            Pragma:
              schema:
                type: string
                example: no-cache
            Expires:
              schema:
                type: integer
                example: '0'
            X-Frame-Options:
              schema:
                type: string
                example: DENY
            Content-Type:
              schema:
                type: string
                example: application/json
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Date:
              schema:
                type: string
                example: Fri, 30 Aug 2024 09:21:13 GMT
            Keep-Alive:
              schema:
                type: string
                example: timeout=60
            Connection:
              schema:
                type: string
                example: keep-alive
          content:
            application/json:
              schema:
                type: object
              example:
                id: 3
                title: Car C
                fuelType: Electric
                price: 33000
                mileage: 12000
                firstRegistration: '2023-06-20T00:00:00.000+00:00'
                createdAt: '2024-08-30T07:35:16.875+00:00'
                updatedAt: null
                new: false
    delete:
      tags:
        - Adverts
      summary: DELETE Delete Advert
      security:
        - bearerAuth: []
      responses:
        '204':
          description: No Content
          headers:
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-XSS-Protection:
              schema:
                type: integer
                example: '0'
            Cache-Control:
              schema:
                type: string
                example: no-cache, no-store, max-age=0, must-revalidate
            Pragma:
              schema:
                type: string
                example: no-cache
            Expires:
              schema:
                type: integer
                example: '0'
            X-Frame-Options:
              schema:
                type: string
                example: DENY
            Date:
              schema:
                type: string
                example: Fri, 30 Aug 2024 09:20:26 GMT
            Keep-Alive:
              schema:
                type: string
                example: timeout=60
            Connection:
              schema:
                type: string
                example: keep-alive
          content:
            text/plain:
              schema:
                type: string
              example: null
  /adverts/7:
    get:
      tags:
        - Adverts
      summary: GET One Advert Second Example
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          headers:
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-XSS-Protection:
              schema:
                type: integer
                example: '0'
            Cache-Control:
              schema:
                type: string
                example: no-cache, no-store, max-age=0, must-revalidate
            Pragma:
              schema:
                type: string
                example: no-cache
            Expires:
              schema:
                type: integer
                example: '0'
            X-Frame-Options:
              schema:
                type: string
                example: DENY
            Content-Type:
              schema:
                type: string
                example: application/json
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Date:
              schema:
                type: string
                example: Fri, 30 Aug 2024 09:19:25 GMT
            Keep-Alive:
              schema:
                type: string
                example: timeout=60
            Connection:
              schema:
                type: string
                example: keep-alive
          content:
            application/json:
              schema:
                type: object
              example:
                id: 7
                title: Car G
                fuelType: Electric
                price: 30000
                mileage: 1000
                firstRegistration: '2023-02-18'
                createdAt: '2024-08-30T07:35:16.875+00:00'
                updatedAt: '2024-08-30T07:35:16.875+00:00'
                new: true
  /adverts/10:
    put:
      tags:
        - Adverts
      summary: PUT Update Advert Error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                title: Car C
                fuelType: Electric
                price: -33000
                mileage: 12000
                firstRegistration: '2023-06-20'
                new: false
      security:
        - bearerAuth: []
      responses:
        '422':
          description: Unprocessable Entity (WebDAV) (RFC 4918)
          headers:
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-XSS-Protection:
              schema:
                type: integer
                example: '0'
            Cache-Control:
              schema:
                type: string
                example: no-cache, no-store, max-age=0, must-revalidate
            Pragma:
              schema:
                type: string
                example: no-cache
            Expires:
              schema:
                type: integer
                example: '0'
            X-Frame-Options:
              schema:
                type: string
                example: DENY
            Content-Type:
              schema:
                type: string
                example: text/plain;charset=UTF-8
            Content-Length:
              schema:
                type: integer
                example: '44'
            Date:
              schema:
                type: string
                example: Fri, 30 Aug 2024 09:19:59 GMT
            Keep-Alive:
              schema:
                type: string
                example: timeout=60
            Connection:
              schema:
                type: string
                example: keep-alive
          content:
            text/plain:
              schema:
                type: string
              example: Price, mileage, and ID must not be negative.
  /users:
    get:
      tags:
        - Users
      summary: GET All Users
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          headers:
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-XSS-Protection:
              schema:
                type: integer
                example: '0'
            Cache-Control:
              schema:
                type: string
                example: no-cache, no-store, max-age=0, must-revalidate
            Pragma:
              schema:
                type: string
                example: no-cache
            Expires:
              schema:
                type: integer
                example: '0'
            X-Frame-Options:
              schema:
                type: string
                example: DENY
            Content-Type:
              schema:
                type: string
                example: application/json
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Date:
              schema:
                type: string
                example: Fri, 30 Aug 2024 09:20:41 GMT
            Keep-Alive:
              schema:
                type: string
                example: timeout=60
            Connection:
              schema:
                type: string
                example: keep-alive
          content:
            application/json:
              schema:
                type: object
              example:
                - id: 1
                  username: Admin
                  password: Admin
                  email: Admin@admin.com
                  createdAt: '2024-08-30T07:35:16.877+00:00'
                  updatedAt: '2024-08-30T07:35:16.877+00:00'
                - id: 2
                  username: Admin2
                  password: Admin2
                  email: Admin2@admin.com
                  createdAt: '2024-08-30T07:35:16.877+00:00'
                  updatedAt: '2024-08-30T07:35:16.877+00:00'
                - id: 3
                  username: testuser22
                  password: testpassword22
                  email: testemail
                  createdAt: '2024-08-30T07:37:17.849+00:00'
                  updatedAt: '2024-08-30T07:37:17.849+00:00'
                - id: 4
                  username: testuser22
                  password: testpassword22
                  email: testemail
                  createdAt: '2024-08-30T07:38:59.284+00:00'
                  updatedAt: '2024-08-30T07:38:59.284+00:00'
                - id: 5
                  username: testuser22
                  password: testpassword22
                  email: testemail
                  createdAt: '2024-08-30T07:40:58.476+00:00'
                  updatedAt: '2024-08-30T07:40:58.476+00:00'
                - id: 6
                  username: testuser22
                  password: testpassword22
                  email: testemail
                  createdAt: '2024-08-30T07:48:07.051+00:00'
                  updatedAt: '2024-08-30T07:48:07.051+00:00'
                - id: 7
                  username: testuser22
                  password: testpassword22
                  email: testemail
                  createdAt: '2024-08-30T07:56:29.839+00:00'
                  updatedAt: '2024-08-30T07:56:29.839+00:00'
                - id: 8
                  username: testuser22
                  password: testpassword22
                  email: testemail
                  createdAt: '2024-08-30T08:23:21.010+00:00'
                  updatedAt: '2024-08-30T08:23:21.010+00:00'
                - id: 9
                  username: testuser22
                  password: testpassword22
                  email: testemail
                  createdAt: '2024-08-30T08:33:05.238+00:00'
                  updatedAt: '2024-08-30T08:33:05.238+00:00'
                - id: 10
                  username: testuser22
                  password: testpassword22
                  email: testemail
                  createdAt: '2024-08-30T08:35:53.031+00:00'
                  updatedAt: '2024-08-30T08:35:53.031+00:00'
                - id: 11
                  username: testuser22
                  password: testpassword22
                  email: testemail
                  createdAt: '2024-08-30T08:36:43.309+00:00'
                  updatedAt: '2024-08-30T08:36:43.309+00:00'
                - id: 12
                  username: testuser22
                  password: testpassword22
                  email: testemail
                  createdAt: '2024-08-30T08:45:14.261+00:00'
                  updatedAt: '2024-08-30T08:45:14.261+00:00'
                - id: 13
                  username: testuser22
                  password: testpassword22
                  email: testemail
                  createdAt: '2024-08-30T08:51:58.942+00:00'
                  updatedAt: '2024-08-30T08:51:58.942+00:00'
  /adverts/17:
    delete:
      tags:
        - Adverts Basic Auth
      summary: DELETE Delete Advert
      security:
        - basicAuth: []
      responses:
        '204':
          description: No Content
          headers:
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-XSS-Protection:
              schema:
                type: integer
                example: '0'
            Cache-Control:
              schema:
                type: string
                example: no-cache, no-store, max-age=0, must-revalidate
            Pragma:
              schema:
                type: string
                example: no-cache
            Expires:
              schema:
                type: integer
                example: '0'
            X-Frame-Options:
              schema:
                type: string
                example: DENY
            Date:
              schema:
                type: string
                example: Fri, 30 Aug 2024 09:21:08 GMT
            Keep-Alive:
              schema:
                type: string
                example: timeout=60
            Connection:
              schema:
                type: string
                example: keep-alive
          content:
            text/plain:
              schema:
                type: string
              example: null
